# Generated by Django 4.2 on 2026-06-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin'), ('nurse', 'Infirmier(e)'), ('patient', 'Patient'), ('pharmacist', 'Pharmacien'), ('lab', 'Laboratoire')], default='patient', max_length=20),
        ),
    ]
