# Generated by Django 4.2 on 2026-05-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maladies', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DispensationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('stock_minimum', models.IntegerField(default=5)),
                ('prix', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100)),
                ('quantite', models.IntegerField()),
                ('date_expiration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_chronic', models.BooleanField(default=False)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('maladie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maladies.maladie')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('duree', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(default=1)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.medication')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacie.prescription')),
            ],
        ),
    ]
