# Generated by Django 4.2 on 2026-05-06 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_medical', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacie', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensation',
            name='Pharmacien',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='is_chronic',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='maladie',
        ),
        migrations.AddField(
            model_name='dispensationitem',
            name='lot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.medicationlot'),
        ),
        migrations.AddField(
            model_name='medication',
            name='unite',
            field=models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sirop', 'Sirop'), ('injection', 'Injection'), ('autre', 'Autre')], default='comprime', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('delivree', 'Délivrée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequence',
            field=models.CharField(default='1 fois par jour', max_length=100),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='prescription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation', to='pharmacie.prescription'),
        ),
        migrations.AlterField(
            model_name='medicationlot',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacie.medication'),
        ),
        migrations.AlterField(
            model_name='medicationlot',
            name='numero_lot',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='suivi_medical.suivimedical'),
        ),
        migrations.AddField(
            model_name='dispensation',
            name='pharmacien',
            field=models.ForeignKey(limit_choices_to={'role': 'pharmacy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
