# Generated by Django 4.2 on 2026-05-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0003_remove_dispensation_pharmacien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='suivi',
            new_name='suivi_medical',
        ),
    ]
