# Generated by Django 4.2 on 2026-05-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0004_rename_suivi_prescription_suivi_medical'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='prix',
            field=models.FloatField(default=0),
        ),
    ]
