# Generated by Django 4.2 on 2026-05-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0005_alter_medication_prix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationlot',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
