# Generated by Django 4.2 on 2026-05-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0006_alter_medicationlot_numero_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='date_prochain_renouvellement',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duree_jours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duree_standard',
            field=models.IntegerField(choices=[(30, '1 mois'), (60, '2 mois'), (90, '3 mois'), (180, '6 mois')], default=30),
        ),
        migrations.AddField(
            model_name='prescription',
            name='est_traitement_chronique',
            field=models.BooleanField(default=False),
        ),
    ]
