# Generated by Django 4.2 on 2026-05-15 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0007_prescription_date_prochain_renouvellement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='est_traitement_chronique',
        ),
    ]
