# Generated by Django 4.2 on 2026-05-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0008_remove_prescription_est_traitement_chronique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='duree',
        ),
    ]
