# Generated by Django 4.2 on 2026-05-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0009_remove_prescriptionitem_duree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='duree_jours',
        ),
    ]
