# Generated by Django 4.2 on 2026-05-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacie', '0010_remove_prescription_duree_jours'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensation',
            name='cachet_pharmacie',
            field=models.ImageField(blank=True, null=True, upload_to='cachets/'),
        ),
    ]
