# Generated by Django 4.2 on 2026-06-04 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacie', '0012_alter_prescription_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='pharmacien',
            field=models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
