# Generated by Django 4.2 on 2026-06-05 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_options_alter_patient_medecin_traitant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suivi_medical', '0010_alter_suivimedical_cd4_and_more'),
        ('pharmacie', '0014_chronic_pharmacy_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispensation',
            options={'ordering': ['-date'], 'verbose_name': 'Dispensation', 'verbose_name_plural': 'Dispensations'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['nom'], 'verbose_name': 'Médicament', 'verbose_name_plural': 'Médicaments'},
        ),
        migrations.AlterModelOptions(
            name='medicationlot',
            options={'ordering': ['date_expiration'], 'verbose_name': 'Lot', 'verbose_name_plural': 'Lots'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-date'], 'verbose_name': 'Prescription', 'verbose_name_plural': 'Prescriptions'},
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='cachet_pharmacie',
            field=models.ImageField(blank=True, null=True, upload_to='cachets/', verbose_name='Cachet pharmacie'),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de dispensation'),
        ),
        migrations.AlterField(
            model_name='dispensation',
            name='pharmacien',
            field=models.ForeignKey(limit_choices_to={'role': 'pharmacist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensations_realisees', to=settings.AUTH_USER_MODEL, verbose_name='Pharmacien'),
        ),
        migrations.AlterField(
            model_name='dispensationitem',
            name='dispensation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacie.dispensation', verbose_name='Dispensation'),
        ),
        migrations.AlterField(
            model_name='dispensationitem',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pharmacie.medicationlot', verbose_name='Lot'),
        ),
        migrations.AlterField(
            model_name='dispensationitem',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pharmacie.medication', verbose_name='Médicament'),
        ),
        migrations.AlterField(
            model_name='dispensationitem',
            name='quantite',
            field=models.IntegerField(verbose_name='Quantité délivrée'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='prix',
            field=models.FloatField(default=0, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='stock_minimum',
            field=models.IntegerField(default=5, verbose_name="Seuil d'alerte"),
        ),
        migrations.AlterField(
            model_name='medication',
            name='unite',
            field=models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sirop', 'Sirop'), ('injection', 'Injection'), ('autre', 'Autre')], default='comprime', max_length=20, verbose_name='Forme'),
        ),
        migrations.AlterField(
            model_name='medicationlot',
            name='date_expiration',
            field=models.DateField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='medicationlot',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='pharmacie.medication', verbose_name='Médicament'),
        ),
        migrations.AlterField(
            model_name='medicationlot',
            name='numero_lot',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='N° de lot'),
        ),
        migrations.AlterField(
            model_name='medicationlot',
            name='quantite',
            field=models.IntegerField(verbose_name='Quantité en stock'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de prescription'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='date_prochain_renouvellement',
            field=models.DateField(blank=True, null=True, verbose_name='Prochain renouvellement'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duree_standard',
            field=models.IntegerField(choices=[(30, '1 mois'), (60, '2 mois'), (90, '3 mois'), (180, '6 mois')], default=30, verbose_name='Fréquence de renouvellement'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medecin',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL, verbose_name='Médecin prescripteur'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='suivi_medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='suivi_medical.suivimedical', verbose_name='Suivi médical'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(max_length=100, verbose_name='Dosage'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacie.medication', verbose_name='Médicament'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacie.prescription', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='quantite',
            field=models.IntegerField(default=1, verbose_name='Quantité par dispensation'),
        ),
    ]
