# Generated by Django 4.2 on 2026-05-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_test', models.CharField(max_length=100)),
                ('resultat', models.TextField()),
                ('valeur', models.FloatField(blank=True, null=True)),
                ('seuil_min', models.FloatField(blank=True, null=True)),
                ('seuil_max', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('anormal', 'Anormal'), ('critique', 'Critique')], max_length=50)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('date_test', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
