# Generated by Django 4.2 on 2026-05-06 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_initial'),
        ('pharmacie', '0003_remove_dispensation_pharmacien_and_more'),
        ('laboratoire', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={'ordering': ['-date_test'], 'verbose_name': 'Analyse de laboratoire', 'verbose_name_plural': 'Analyses de laboratoire'},
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='is_abnormal',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='lab_technicien',
        ),
        migrations.AddField(
            model_name='labtest',
            name='is_validated',
            field=models.BooleanField(default=False, verbose_name='Résultat validé'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_realisees', to=settings.AUTH_USER_MODEL, verbose_name='Laborantin'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='unite',
            field=models.CharField(blank=True, max_length=30, verbose_name='Unité'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='date_test',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date de l'analyse"),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='pharmacie.prescription', verbose_name='Prescription liée'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='resultat',
            field=models.TextField(blank=True, verbose_name='Résultat (texte)'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='seuil_max',
            field=models.FloatField(blank=True, null=True, verbose_name='Seuil maximum normal'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='seuil_min',
            field=models.FloatField(blank=True, null=True, verbose_name='Seuil minimum normal'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('normal', 'Normal'), ('anormal', 'Anormal'), ('critique', 'Critique')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='type_test',
            field=models.CharField(max_length=100, verbose_name="Type d'analyse"),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='valeur',
            field=models.FloatField(blank=True, null=True, verbose_name='Valeur mesurée'),
        ),
    ]
