# Generated by Django 4.2 on 2026-05-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_medical', '0003_remove_ordonnance_medecin_remove_ordonnance_patient_and_more'),
        ('laboratoire', '0003_alter_labtest_options_remove_labtest_is_abnormal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='is_abnormal',
            field=models.BooleanField(default=False, verbose_name='Valeur anormale'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='suivi_medical.suivimedical'),
        ),
    ]
