# Generated by Django 4.2 on 2026-05-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maladies', '0003_remove_maladie_seuil_alerte_and_more'),
        ('laboratoire', '0004_labtest_is_abnormal_labtest_suivi'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='maladies.maladie'),
        ),
    ]
