# Generated by Django 4.2 on 2026-05-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0005_labtest_maladie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='is_abnormal',
            field=models.BooleanField(default=False),
        ),
    ]
