# Generated by Django 4.2 on 2026-05-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratoire', '0006_alter_labtest_is_abnormal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labtest',
            options={},
        ),
    ]
