# Generated by Django 4.2 on 2026-06-05 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maladies', '0007_alter_patientmaladie_options_and_more'),
        ('suivi_medical', '0008_suivimedical_type_suivi'),
        ('pharmacie', '0013_fix_dispensation_pharmacist_role'),
        ('laboratoire', '0008_add_prescripteur_urgence_interpretation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date_test',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='maladie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='maladies.maladie', verbose_name='Maladie liée'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='pharmacie.prescription', verbose_name='Ordonnance médicaments liée'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='suivi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='suivi_medical.suivimedical', verbose_name='Suivi médical lié'),
        ),
    ]
