# Generated by Django 4.2 on 2026-05-18 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_initial'),
        ('alertes_notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='resolved',
            new_name='is_resolved',
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='body',
            new_name='body_template',
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='subject',
            new_name='title_template',
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(choices=[('notification', 'Notification'), ('alert', 'Alerte'), ('reminder', 'Rappel')], default=False, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Alerte'), ('urgent', 'Urgent'), ('reminder', 'Rappel')], default='info', max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
