# Generated by Django 4.2 on 2026-05-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_options'),
        ('alertes_notifications', '0002_rename_resolved_alert_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment'),
        ),
    ]
