# Generated by Django 4.2 on 2026-05-18 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alertes_notifications', '0003_notification_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='body_template',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='messagetemplate',
            old_name='title_template',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='messagetemplate',
            name='name',
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='code',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(choices=[('alert', 'Alerte'), ('notification', 'Notification'), ('info', 'Information'), ('warning', 'Warning')], default='info', max_length=20),
        ),
    ]
