# Generated by Django 4.2 on 2026-05-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertes_notifications', '0005_notification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='level',
            field=models.CharField(default='info', max_length=20),
        ),
    ]
