# Generated by Django 4.2 on 2026-06-05 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patient_options_alter_patient_medecin_traitant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alertes_notifications', '0007_chronic_alert_improvements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Alerte médicale', 'verbose_name_plural': 'Alertes médicales'},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'ordering': ['code'], 'verbose_name': 'Modèle de message', 'verbose_name_plural': 'Modèles de messages'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='is_resolved',
            field=models.BooleanField(default=False, verbose_name='Résolue'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='content',
            field=models.TextField(verbose_name='Contenu (variables: {{patient_nom}}, {{valeur}}, {{seuil}}, {{unite}}, {{date}})'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='type',
            field=models.CharField(choices=[('alert', 'Alerte'), ('notification', 'Notification'), ('info', 'Information'), ('warning', 'Avertissement')], default='info', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créé le'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('urgent', 'Urgent')], default='info', max_length=20, verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
    ]
