# Generated by Django 4.2 on 2026-05-06 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('seuil_alerte', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientMaladie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traitement', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('stable', 'Stable'), ('guérie', 'Guérie')], max_length=20)),
                ('date_diagnostic', models.DateField()),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='maladies.maladie')),
            ],
        ),
    ]
