# Generated by Django 4.2 on 2026-05-07 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maladies', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maladie',
            name='seuil_alerte',
        ),
        migrations.RemoveField(
            model_name='patientmaladie',
            name='traitement',
        ),
        migrations.AddField(
            model_name='maladie',
            name='type',
            field=models.CharField(choices=[('vih', 'VIH/SIDA'), ('diabete', 'Diabète'), ('hta', 'Hypertension'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AddField(
            model_name='patientmaladie',
            name='observations',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='maladie',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patientmaladie',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('stable', 'Stable'), ('guérie', 'Guérie')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='SeuilAlerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur', models.CharField(max_length=100)),
                ('min_valeur', models.FloatField(blank=True, null=True)),
                ('max_valeur', models.FloatField(blank=True, null=True)),
                ('patient_maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seuils', to='maladies.patientmaladie')),
            ],
        ),
    ]
