# Generated by Django 4.2 on 2026-05-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maladies', '0003_remove_maladie_seuil_alerte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maladie',
            name='type',
        ),
    ]
