# Generated by Django 4.2 on 2026-05-16 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        ('maladies', '0004_remove_maladie_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seuilalerte',
            options={'verbose_name': "Seuil d'alerte", 'verbose_name_plural': "Seuils d'alerte"},
        ),
        migrations.AddField(
            model_name='maladie',
            name='type',
            field=models.CharField(choices=[('vih', 'VIH/SIDA'), ('diabete', 'Diabète'), ('hypertention', 'Hypertension'), ('asthme', 'Asthme'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
        migrations.AddField(
            model_name='patientmaladie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='patientmaladie',
            unique_together={('patient', 'maladie')},
        ),
    ]
