# Generated by Django 4.2 on 2026-05-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maladies', '0005_alter_seuilalerte_options_maladie_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maladie',
            name='type',
            field=models.CharField(choices=[('infectieuse', 'Infectieuse'), ('metabolique', 'Métabolique'), ('respiratoire', 'Respiratoire'), ('cardiovasculaire', 'cardiovasculaire'), ('neurologique', 'Neurologique'), ('auto-immune ', 'auto-immune'), ('rénale', 'rénale'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
