# Generated by Django 4.2 on 2026-05-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maladies', '0006_alter_maladie_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientmaladie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='patientmaladie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
