# Generated by Django 4.2 on 2026-05-20 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
    ]
