# Generated by Django 4.2 on 2026-05-20 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0004_patient_adresse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='compte_patient',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'patient'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profil_patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
