# Generated by Django 4.2 on 2026-06-04 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_alter_patient_compte_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['-date_creation']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='medecin_traitant',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_suivis', to=settings.AUTH_USER_MODEL),
        ),
    ]
