# Generated by Django 4.2 on 2026-05-06 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maladies', '0002_initial'),
        ('pharmacie', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LigneOrdonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(max_length=100)),
                ('frequence', models.CharField(max_length=100)),
                ('duree_jours', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('est_delivree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SuiviMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_suivi', models.DateTimeField(default=django.utils.timezone.now)),
                ('poids', models.FloatField(blank=True, help_text='kg', null=True)),
                ('taille', models.FloatField(blank=True, help_text='cm', null=True)),
                ('imc', models.FloatField(blank=True, editable=False, null=True)),
                ('tension', models.CharField(blank=True, help_text='ex: 120/80', max_length=20, null=True)),
                ('glycemie', models.FloatField(blank=True, help_text='g/L', null=True)),
                ('cd4', models.FloatField(blank=True, help_text='cellules/mm³', null=True)),
                ('charge_virale', models.FloatField(blank=True, help_text='copies/mL', null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('stable', 'Stable'), ('ameliore', 'Amélioré'), ('critique', 'Critique')], default='stable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suivi médical',
                'ordering': ['-date_suivi'],
            },
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posologie', models.CharField(help_text='ex: 500mg', max_length=100)),
                ('frequence', models.CharField(choices=[('1x_jour', '1 fois par jour'), ('2x_jour', '2 fois par jour'), ('3x_jour', '3 fois par jour'), ('1x_semaine', '1 fois par semaine'), ('autre', 'Autre')], default='1x_jour', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('maladie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='maladies.maladie')),
                ('medicament', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements', to='pharmacie.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traitements', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Traitement',
            },
        ),
    ]
