# Generated by Django 4.2 on 2026-05-06 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacie', '0002_initial'),
        ('patients', '0002_initial'),
        ('suivi_medical', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='traitement',
            name='prescrit_par',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traitements_prescrits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suivimedical',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suivimedical',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='medecin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='suivi',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ordonnance', to='suivi_medical.suivimedical'),
        ),
        migrations.AddField(
            model_name='ligneordonnance',
            name='medicament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacie.medication'),
        ),
        migrations.AddField(
            model_name='ligneordonnance',
            name='ordonnance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='suivi_medical.ordonnance'),
        ),
    ]
