# Generated by Django 4.2 on 2026-05-06 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('suivi_medical', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordonnance',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='suivi',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='maladie',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='traitement',
            name='prescrit_par',
        ),
        migrations.AlterModelOptions(
            name='suivimedical',
            options={},
        ),
        migrations.AddField(
            model_name='suivimedical',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi', to='appointments.appointment'),
        ),
        migrations.DeleteModel(
            name='LigneOrdonnance',
        ),
        migrations.DeleteModel(
            name='Ordonnance',
        ),
        migrations.DeleteModel(
            name='Traitement',
        ),
    ]
