# Generated by Django 4.2 on 2026-05-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_medical', '0003_remove_ordonnance_medecin_remove_ordonnance_patient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suivimedical',
            options={'ordering': ['-date_suivi'], 'verbose_name': 'Suivi médical', 'verbose_name_plural': 'Suivis médicaux'},
        ),
    ]
