# Generated by Django 4.2 on 2026-05-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
        ('suivi_medical', '0004_alter_suivimedical_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suivimedical',
            options={'ordering': ['-created_at'], 'verbose_name': 'Suivi médical', 'verbose_name_plural': 'Suivis médicaux'},
        ),
        migrations.RemoveField(
            model_name='suivimedical',
            name='date_suivi',
        ),
        migrations.RemoveField(
            model_name='suivimedical',
            name='tension',
        ),
        migrations.AddField(
            model_name='suivimedical',
            name='tension_diastolique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suivimedical',
            name='tension_systolique',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suivimedical',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivi', to='appointments.appointment'),
        ),
    ]
