# Generated by Django 4.2 on 2026-05-18 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_unique_doctor_appointment_and_more'),
        ('suivi_medical', '0005_alter_suivimedical_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivimedical',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to='appointments.appointment'),
        ),
    ]
