# Generated by Django 4.2 on 2026-05-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_medical', '0006_alter_suivimedical_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivimedical',
            name='cd4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suivimedical',
            name='charge_virale',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suivimedical',
            name='glycemie',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suivimedical',
            name='poids',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suivimedical',
            name='taille',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
