# Generated by Django 4.2 on 2026-05-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_medical', '0007_alter_suivimedical_cd4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivimedical',
            name='type_suivi',
            field=models.CharField(choices=[('rdv', 'Avec rendez-vous'), ('direct', 'Sans rendez-vous')], default='rdv', max_length=10),
        ),
    ]
