# Generated by Django 4.2 on 2026-06-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_medical', '0009_add_biological_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivimedical',
            name='cd4',
            field=models.FloatField(blank=True, null=True, verbose_name='CD4 (cells/mm³)'),
        ),
        migrations.AlterField(
            model_name='suivimedical',
            name='charge_virale',
            field=models.FloatField(blank=True, null=True, verbose_name='Charge virale (copies/mL)'),
        ),
        migrations.AlterField(
            model_name='suivimedical',
            name='glycemie',
            field=models.FloatField(blank=True, null=True, verbose_name='Glycémie (g/L)'),
        ),
    ]
